# Generated by Django 5.0.6 on 2024-09-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
